# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Rants about programming..."
description: > # this means to ignore newlines until "email:"
   Coding, Japan and general rants from Toyko...

email: dymczyk@gmail.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Mateusz Dymczyk'
author: 'Mateusz Dymczyk'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.puroguramingu.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mdymczyk
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mdymczyk
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
      comments: true
